import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { assertCustomizationSpec, type CustomizationSpec } from "@oae/spec-schema";

export interface CompileOptions {
  repoRoot: string;
  generatedAddonsDir?: string;
  artifactsDir?: string;
  defaultModuleName?: string;
}

export interface CompileResult {
  moduleName: string;
  modulePath: string;
  artifactPaths: string[];
  manifestPath: string;
}

function toSnakeCase(input: string): string {
  return input
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .replace(/_{2,}/g, "_");
}

function deriveModuleName(spec: CustomizationSpec, explicit?: string): string {
  if (explicit) {
    return explicit;
  }

  const titleSlug = toSnakeCase(spec.request.title).slice(0, 40);
  const normalized = titleSlug.startsWith("oae_") ? titleSlug : `oae_${titleSlug}`;
  return normalized || "oae_generated_customization";
}

function renderManifest(moduleName: string, spec: CustomizationSpec): string {
  const depends = Array.from(new Set(spec.scope.target_modules)).sort();
  const dependsPy = depends.length ? depends.map((dep) => `        \"${dep}\"`).join(",\n") : "        \"base\"";

  return `{
    \"name\": \"${moduleName}\",
    \"summary\": \"Generated by Odoo AI Edition deterministic compiler\",
    \"version\": \"19.0.1.0.0\",
    \"category\": \"Customization\",
    \"author\": \"Odoo AI Edition\",
    \"license\": \"LGPL-3\",
    \"depends\": [\n${dependsPy}\n    ],
    \"data\": [
        \"security/ir.model.access.csv\",
        \"views/menu.xml\"
    ],
    \"installable\": True,
    \"application\": False
}
`;
}

function renderReadme(moduleName: string, spec: CustomizationSpec): string {
  return `# ${moduleName}

## Purpose
${spec.request.business_goal}

## Affected Base Modules
${spec.scope.target_modules.map((moduleNameLine: string) => `- ${moduleNameLine}`).join("\n") || "- base"}

## Configuration Steps
1. Install module in sandbox.
2. Run generated tests in \`tests/\`.
3. Validate ACL behavior before promotion.

## Permissions Model
- Explicit ACL and group files must be reviewed and approved.

## Operational Notes
- Generated from canonical spec \`${spec.request.title}\`.
- Any migration logic must be added in \`migrations/\`.

## Test Instructions
- Run Odoo install and upgrade tests.
- Run ACL and workflow coverage tests for changed behavior.
`;
}

function renderModelStub(moduleName: string): string {
  return `from odoo import api, fields, models


class ${moduleName
    .split("_")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("")}Service(models.AbstractModel):
    _name = \"${moduleName}.service\"
    _description = \"Generated service extension point\"

    @api.model
    def ping(self):
        return {\"status\": \"ok\", \"module\": \"${moduleName}\"}
`;
}

function renderAccessCsv(moduleName: string): string {
  return [
    "id,name,model_id:id,group_id:id,perm_read,perm_write,perm_create,perm_unlink",
    `access_${moduleName}_service,access_${moduleName}_service,model_${moduleName.replaceAll("_", "_")}_service,base.group_system,1,1,1,0`
  ].join("\n");
}

function renderMenuXml(moduleName: string): string {
  return `<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<odoo>
  <menuitem id=\"menu_${moduleName}\" name=\"${moduleName}\" parent=\"base.menu_custom\" sequence=\"95\" />
</odoo>
`;
}

function renderTest(moduleName: string): string {
  return `from odoo.tests import tagged
from odoo.tests.common import TransactionCase


@tagged("post_install", "-at_install")
class Test${moduleName
    .split("_")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("")}(TransactionCase):
    def test_generated_service_ping(self):
        service = self.env[\"${moduleName}.service\"]
        result = service.ping()
        self.assertEqual(result[\"status\"], \"ok\")
`;
}

async function writeModuleSkeleton(modulePath: string, moduleName: string, spec: CustomizationSpec): Promise<void> {
  const dirs = [
    "models",
    "views",
    "security",
    "data",
    "report",
    "controllers",
    "static",
    "tests",
    "migrations"
  ];

  await mkdir(modulePath, { recursive: true });
  await Promise.all(dirs.map((dir) => mkdir(path.join(modulePath, dir), { recursive: true })));

  await Promise.all([
    writeFile(path.join(modulePath, "__init__.py"), "from . import models\n", "utf8"),
    writeFile(path.join(modulePath, "__manifest__.py"), renderManifest(moduleName, spec), "utf8"),
    writeFile(path.join(modulePath, "README.md"), renderReadme(moduleName, spec), "utf8"),
    writeFile(path.join(modulePath, "models", "__init__.py"), "from . import generated_service\n", "utf8"),
    writeFile(path.join(modulePath, "models", "generated_service.py"), renderModelStub(moduleName), "utf8"),
    writeFile(path.join(modulePath, "security", "ir.model.access.csv"), renderAccessCsv(moduleName), "utf8"),
    writeFile(path.join(modulePath, "views", "menu.xml"), renderMenuXml(moduleName), "utf8"),
    writeFile(path.join(modulePath, "tests", "test_generated_service.py"), renderTest(moduleName), "utf8"),
    writeFile(path.join(modulePath, "migrations", "README.md"), "Add migration scripts and rollback notes here.\n", "utf8")
  ]);
}

async function writeBuildArtifacts(
  artifactsDir: string,
  moduleName: string,
  spec: CustomizationSpec
): Promise<{ manifestPath: string; artifactPaths: string[] }> {
  await mkdir(artifactsDir, { recursive: true });

  const now = new Date().toISOString();
  const buildManifestPath = path.join(artifactsDir, "build-manifest.json");
  const riskReportPath = path.join(artifactsDir, "risk-report.json");
  const affectedEntitiesPath = path.join(artifactsDir, "affected-entities.json");
  const diffSummaryPath = path.join(artifactsDir, "diff-summary.md");
  const functionalSummaryPath = path.join(artifactsDir, "functional-summary.md");
  const technicalSummaryPath = path.join(artifactsDir, "technical-summary.md");
  const uatChecklistPath = path.join(artifactsDir, "uat-checklist.md");
  const rollbackPlanPath = path.join(artifactsDir, "rollback-plan.md");

  const buildManifest = {
    kind: "oae_build_manifest",
    version: "1.0",
    generated_at: now,
    module_name: moduleName,
    workspace_id: spec.workspace_id,
    instance_id: spec.instance_id,
    request_title: spec.request.title,
    test_requirements: spec.tests.required,
    deliverables: spec.deliverables
  };

  const riskReport = {
    level: spec.risk.level,
    elevated: spec.risk.elevated,
    reasons: spec.risk.reasons,
    approval_required: spec.risk.approval_required
  };

  const affectedEntities = {
    modules: spec.scope.target_modules,
    environments: spec.scope.target_environments,
    sections: Object.keys(spec.changes).filter((key) => spec.changes[key as keyof typeof spec.changes].length > 0)
  };

  await Promise.all([
    writeFile(buildManifestPath, JSON.stringify(buildManifest, null, 2), "utf8"),
    writeFile(riskReportPath, JSON.stringify(riskReport, null, 2), "utf8"),
    writeFile(affectedEntitiesPath, JSON.stringify(affectedEntities, null, 2), "utf8"),
    writeFile(diffSummaryPath, "# Diff Summary\n\nDeterministic baseline scaffold generated.\n", "utf8"),
    writeFile(functionalSummaryPath, `# Functional Summary\n\n${spec.request.business_goal}\n`, "utf8"),
    writeFile(technicalSummaryPath, `# Technical Summary\n\nGenerated module: \`${moduleName}\`\n`, "utf8"),
    writeFile(uatChecklistPath, "# UAT Checklist\n\n- [ ] Install module in sandbox\n- [ ] Validate workflow path\n- [ ] Validate ACL constraints\n", "utf8"),
    writeFile(rollbackPlanPath, "# Rollback Plan\n\n1. Revert module commit.\n2. Run compensating migration if needed.\n3. Restore snapshot if migration touched persisted records.\n", "utf8")
  ]);

  return {
    manifestPath: buildManifestPath,
    artifactPaths: [
      buildManifestPath,
      riskReportPath,
      affectedEntitiesPath,
      diffSummaryPath,
      functionalSummaryPath,
      technicalSummaryPath,
      uatChecklistPath,
      rollbackPlanPath
    ]
  };
}

export async function compileCustomizationSpec(
  specInput: unknown,
  options: CompileOptions
): Promise<CompileResult> {
  const spec = assertCustomizationSpec(specInput);
  const moduleName = deriveModuleName(spec, options.defaultModuleName);
  const generatedAddonsDir = options.generatedAddonsDir ?? path.join(options.repoRoot, "addons", "generated");
  const artifactsDir = options.artifactsDir ?? path.join(options.repoRoot, "artifacts", moduleName);

  const modulePath = path.join(generatedAddonsDir, moduleName);
  await writeModuleSkeleton(modulePath, moduleName, spec);
  const artifactOutput = await writeBuildArtifacts(artifactsDir, moduleName, spec);

  return {
    moduleName,
    modulePath,
    artifactPaths: artifactOutput.artifactPaths,
    manifestPath: artifactOutput.manifestPath
  };
}
