[options]
addons_path = /mnt/extra-addons/bridge,/mnt/extra-addons/generated,/mnt/extra-addons/custom,/mnt/extra-addons/test_support,/usr/lib/python3/dist-packages/odoo/addons
admin_passwd = ${ODOO_ADMIN_PASSWORD}
db_host = odoo-db
db_port = 5432
db_user = ${ODOO_DB_USER}
db_password = ${ODOO_DB_PASSWORD}
proxy_mode = True
log_level = info
list_db = True
without_demo = all
